# Generated by Django 5.2.12 on 2026-03-30 22:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_name', models.CharField(blank=True, help_text='Example: briefcase, heart, globe, book', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParallelLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('divergence_date', models.DateField()),
                ('starting_choice', models.CharField(help_text='The key decision that changed this life path.', max_length=200)),
                ('summary', models.TextField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('realism_score', models.PositiveIntegerField(help_text='Rate how realistic this path feels from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(related_name='parallel_lives', to='parallel_lives.lifedomain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallel_lives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DivergenceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_title', models.CharField(max_length=120)),
                ('real_world_path', models.TextField()),
                ('alternate_path', models.TextField()),
                ('reasoning', models.TextField()),
                ('emotional_weight', models.PositiveSmallIntegerField(help_text='How emotionally important is this divergence?', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parallel_life', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='parallel_lives.parallellife')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parallel_life', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='parallel_lives.parallellife')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'parallel_life'), name='unique_user_path_follow')],
            },
        ),
    ]
